name: CIProject

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11  # Specify the Python version you want to use


    # Poetry install not installing dependencies correctly so manually installed
    - name: Install dependencies
      run: |
        pip install poetry
        pip install pytest
        pip install flake8
        pip install pytest-cov

    - name: Poetry install
      run: |
        cd RefactorCode
        poetry install
      
    - name: Run test
      run: pytest > ../test_results.txt || true

    - name: Run tests with coverage
      run: pytest --cov=./RefactorCode --cov-report=xml:./RefactorCode/CoverageReport/coverage.xml
        
    - name: Run Flake 8
      run: |
        cd RefactorCode
        flake8 > ../flake8_report.txt || true
